name: e_commerce
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  dio: ^5.8.0+1
  logger: ^2.0.1
  shared_preferences: ^2.3.5
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  google_fonts: ^6.2.1
  flutter_stripe: ^11.5.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^6.3.0
  http: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
