name: "Build & Release"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest # Use Linux for Android to save costs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Run Flutter Doctor
        run: flutter doctor -v
      - name: Build APK
        run: flutter build apk --release --split-per-abi
      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: build/app/outputs/apk/release/*.apk

  build-ios:
    name: Build iOS
    runs-on: macos-latest # Required for iOS builds
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Run Flutter Doctor
        run: flutter doctor -v
      - name: Build iOS
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos/app.ipa

  release:
    name: Create Release
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Android Artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-apks
          path: build/app/outputs/apk/release
      - name: Download iOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
