name: Flutter CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  android-build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          # This version was updated to a newer version (3.32.8)
          # to meet the project's Dart SDK requirements as suggested by the error log.
          flutter-version: '3.32.8'
          cache: true

      - name: Verify Flutter Setup
        run: |
          flutter --version
          echo "Flutter setup completed for version 3.32.8"

      - name: Install dependencies
        run: flutter pub get

      - name: Set up key.properties
        run: |
          # The working-directory is already 'android', so we don't need to specify 'android/'.
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" > key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> key.properties
          echo "${{ secrets.STORE_FILE_CONTENT }}" | base64 --decode > key.jks
        working-directory: ./android

      - name: Set up local.properties
        run: |
          # The working-directory is already 'android', so we don't need to specify 'android/'.
          echo "flutter.sdk=$FLUTTER_ROOT" > local.properties
        working-directory: ./android

      - name: Build Release AAB and APK
        run: |
          flutter build appbundle --release
          flutter build apk --release

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 7

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          # Corrected the secret name to the standard GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
